### ISSUE TITLE
Fixed PHP 8 modifier "default"

### ISSUE THREAD

**Issue by juvenrui** [smarty-php/smarty#617]
PHP 8 has deprecated for "@". But modifier "default" is not compatible. 

plugins/modifiercompiler.default.php
`// $output = '(($tmp = @' . $output . ')===null||$tmp===\'\' ? ' . $param . ' : $tmp)';`
`$output = '(($tmp = ' . $output . ' ?? null)===null||$tmp===\'\' ? ' . $param . ' : $tmp)';  // edit by 2020.12.1 -- fixed PHP 8`

**Comment by scottchiefbaker** [comment]
I don't see `@` being [deprecated](https://www.php.net/manual/en/migration80.deprecated.php). Where did you see that?

**Comment by juvenrui** [comment]
> I don't see `@` being [deprecated](https://www.php.net/manual/en/migration80.deprecated.php). Where did you see that?

Really, "The @ operator will no longer silence fatal errors ......" (https://www.php.net/manual/zh/migration80.incompatible.php)

thanks!

**Comment by timmit-nl** [comment]
maybe it is time for smarty v4 so it can shake of any support for pre php7.2. As it whould be a challange to get full compatibility for php8 en below 7.1 (and those are all EOL anyway)

**Comment by Bigbear7** [comment]
Well, I think given that PHP 8 is out now, it would be good with a 3.1.37 release that fixes the most urgent hiccups. For a Smarty 4 version I think that PHP 7.4 as a minimum could be an idea given features like typed properties etc.

**Comment by omexlu** [comment]
Does smarty run on php8 already? :)

**Comment by juvenrui** [comment]
> Does smarty run on php8 already? :)

Yes, version is 3.1.36，PHP8 is run OK! 😀

**Comment by chriswheeler** [comment]
3.1.36 doesn't work for me with PHP8, it needs some fixes which appear to be on master (https://github.com/smarty-php/smarty/commit/c295786e43735802a1a22d22bc6d72153d19af46) - is there an ETA for 3.1.37?

**Comment by omexlu** [comment]
> 3.1.36 doesn't work for me with PHP8, it needs some fixes which appear to be on master ([c295786](https://github.com/smarty-php/smarty/commit/c295786e43735802a1a22d22bc6d72153d19af46)) - is there an ETA for 3.1.37?

What exactly is not working for you? I have not noticed any problems under php 8.0.0 so far?

**Comment by chriswheeler** [comment]
I get this error from a smarty generated compiled template: 

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Smarty_Internal_ErrorHandler::mutingErrorHandler(), 4 passed and exactly 5 expected in /home/redacted/public_html/system/composer/vendor/smarty/smarty/libs/sysplugins/smarty_internal_errorhandler.php:68

The line in the .tpl.php file which caused this was calling a static method of a class registered with smarty->registerClass()

**Comment by omexlu** [comment]
I dont have any issues with php8 until now.

**Comment by bhsmither** [comment]
chriswheeler, please see:
https://github.com/smarty-php/smarty/pull/608/commits/e12895359b5c7969923dbfa62fe2f507ee399903
https://www.php.net/manual/en/function.set-error-handler.php errcontext warning

**Comment by chriswheeler** [comment]
@bhsmither just an ETA on when that fix will make it into a release - 3.1.37 I assume?

**Comment by timmit-nl** [comment]
Just to add to the topic starter:

`            $output = '(($tmp = ' . $output . ' ?? null)===null||$tmp===\'\' ? (' . $param . ' ?? null) : $tmp)'; // edit by 2020.12.1 -- fixed PHP 8 (https://github.com/smarty-php/smarty/issues/617)`

has support for more default options and those also can be unset. So it is the same fix you did only also for the params:
it he array is empty or not set at all, this will work without any errors:

`{$array.layer1.DT_KVERVAL|default: $array.DT_KVERVAL: ''}`

we currently extend the template_plugin_modifiercompiler_default so we are not raising any errors on airbrake as it is also ignoring `@`.

**Comment by wisskid** [comment]
This seems to be a duplicate of #605

**Comment by wisskid** [comment]
@timmit-nl sorry, I should have closed the other one as that one was already fixed. Reopening this one.

**Comment by timmit-nl** [comment]
no problem. I can make a merge request, but it is not compatible with php below 7.0. So there must be some kind of discussion before that how to handle legacy php. Does smarty drop it for 4.x.x (so if you want to use legacy php, use 3.x.x.) Or make we an legacy switch and check if we an a legacy version and serve a different version?

**Comment by wisskid** [comment]
I plan to drop support for php below 7.1 or 7.2 in Smarty 4 to be able to support PHP8.

Simon

**Comment by juvenrui** [comment]
Upgrade v3.1.37, the PHP8 output variable throw: 'Warning: Undefined array key "blabla"'

`// development environment
ini_set('display_errors', '1');

I have set a custom error handler function with set_error_handler():
set_error_handler(function ($severity, $message, $file, $line) {
    if ((error_reporting() & $severity) !== $severity) {
        return false;
    }
    throw new \ErrorException($message, 0, $severity, $file, $line);
});`

I think, modifiercompiler.default.php use '@', set_error_handler() will still get called (https://www.php.net/manual/en/language.operators.errorcontrol.php).

My temporary solution, edit libs/plugins/modifiercompiler.default.php:
/ $output = '(($tmp = @' . $output . ')===null||$tmp===\'\' ? ' . $param . ' : $tmp)';
if (version_compare(PHP_VERSION, '7.0.0') >= 0) {
    $output = '(($tmp = ' . $output . ' ?? null)===null||$tmp===\'\' ? ' . $param . ' : $tmp)';
} else {
    $output = '!isset(' . $output . ') || ' . $output . ' === null || ' . $output . ' === \'\' ? ' . $param . ' : ' . $output;
}

**Comment by juvenrui** [comment]
Upgrade v3.1.37, the PHP8 output variable throw: 'Warning: Undefined array key "blabla"'

I have set a custom error handler function with set_error_handler():
```// development environment
ini_set('display_errors', '1');

set_error_handler(function ($severity, $message, $file, $line) {
    if ((error_reporting() & $severity) !== $severity) {
        return false;
    }
    throw new \ErrorException($message, 0, $severity, $file, $line);
});
```

I think, modifiercompiler.default.php use '@', set_error_handler() will still get called (https://www.php.net/manual/en/language.operators.errorcontrol.php).

My temporary solution, edit libs/plugins/modifiercompiler.default.php:
```
//$output = '(($tmp = @' . $output . ')===null||$tmp===\'\' ? ' . $param . ' : $tmp)';
if (version_compare(PHP_VERSION, '7.0.0') >= 0) {
    $output = '(($tmp = ' . $output . ' ?? null)===null||$tmp===\'\' ? ' . $param . ' : $tmp)';
} else {
    $output = '!isset(' . $output . ') || ' . $output . ' === null || ' . $output . ' === \'\' ? ' . $param . ' : ' . $output;
}
```

**Comment by timmit-nl** [comment]
> Upgrade v3.1.37, the PHP8 output variable throw: 'Warning: Undefined array key "blabla"'
> 
> I have set a custom error handler function with set_error_handler():
> 
> ```
> ini_set('display_errors', '1');
> 
> set_error_handler(function ($severity, $message, $file, $line) {
>     if ((error_reporting() & $severity) !== $severity) {
>         return false;
>     }
>     throw new \ErrorException($message, 0, $severity, $file, $line);
> });
> ```
> 
> I think, modifiercompiler.default.php use '@', set_error_handler() will still get called (https://www.php.net/manual/en/language.operators.errorcontrol.php).
> 
> My temporary solution, edit libs/plugins/modifiercompiler.default.php:
> 
> ```
> //$output = '(($tmp = @' . $output . ')===null||$tmp===\'\' ? ' . $param . ' : $tmp)';
> if (version_compare(PHP_VERSION, '7.0.0') >= 0) {
>     $output = '(($tmp = ' . $output . ' ?? null)===null||$tmp===\'\' ? ' . $param . ' : $tmp)';
> } else {
>     $output = '!isset(' . $output . ') || ' . $output . ' === null || ' . $output . ' === \'\' ? ' . $param . ' : ' . $output;
> }
> ```
if you use for the 7.0 modifier
$output = '(($tmp = ' . $output . ' ?? null)===null||$tmp===\'\' ? (' . $param . ' ?? null) : $tmp)'; 
```
//$output = '(($tmp = @' . $output . ')===null||$tmp===\'\' ? ' . $param . ' : $tmp)';
if (version_compare(PHP_VERSION, '7.0.0') >= 0) {
    $output = '(($tmp = ' . $output . ' ?? null)===null||$tmp===\'\' ? (' . $param . ' ?? null) : $tmp)'; 
} else {
    $output = '!isset(' . $output . ') || ' . $output . ' === null || ' . $output . ' === \'\' ? ' . $param . ' : ' . $output;
}
```
you can handle also unset default fallback

**Comment by wisskid** [comment]
@timmit-nl please see #629

**Comment by wisskid** [comment]
At everyone here: please give #629 a go and tell me what you think.

**Comment by chriswheeler** [comment]
With PHP 8.0.1 and smarty/dev-feature/php8-support:

|default now works well, without any PHP messages logged, so this now works:

`{$request.get.location|default:$superglobal.session.location|default'Default locaton'|htmlspecialchars}`

However, I have quite a places where I have instead something like this:

`{if $request.get.location}{$request.get.location|htmlspecialchars}{else}{$superglobal.session.location|htmlspecialchars}{/if}`

Which now give the following message:

`PHP Warning:  Undefined array key "location"`

Prior to PHP8 there were not log messages. Was this intended to be fixed in #629, if not I think it should be for Smarty 4 somehow, otherwise I have a lot of templates to update!

**Comment by wisskid** [comment]
@chriswheeler I'll have a look

**Comment by bhsmither** [comment]
Is the solution to this issue would be to fix "Undefined array key"?

I am coming across this with PHP8 and, for example, this template code:
```
<input type="text" name="global[dbhost]" id="form-dbhost" value="{$FORM.global.dbhost}" class="textbox required" />
```
where $FORM is not as yet assigned anything in the script.

Once compiled, the output stops at:
```
<?php echo $_smarty_tpl->tpl_vars['FORM']->value['global']['dbhost'];?>
```
and the errors:
```
Warning 	Undefined array key "FORM"
Warning 	Attempt to read property "value" on null
Warning 	Trying to access array offset on value of type null
Warning 	Trying to access array offset on value of type null
```

**Comment by juvenrui** [comment]
> {$FORM.global.dbhost}

try this:  {$FORM.global.dbhost|default:''}

**Comment by bhsmither** [comment]
I could, but I am asserting that this - compiling/rendering a non-existsent variable object - wasn't any kind of problem under PHP7.4.

However, that particular installation of a program using Smarty running under PHP7.4 also had muteExpectedErrors() and a proper error_handler and exception_handler.

This problem shows up running Smarty's Demo under PHP8 - having added that `<input>` tag as a test.

**Comment by timmit-nl** [comment]
we have those errors also under 7.4 and lower. Therefore we use `|default:''` everywhere.

Maybe because we have the higest error reporting setting, so get all errors. We like an errorless code, also without any notices or other not breaking errors ;-)

**Comment by Bigbear7** [comment]
Well, I just upgraded to Smarty 3.1.38 for our testsite that runs PHP 8.0. And in the logs we get:
- PHP Warning: Undefined array key

On PHP 7.4 that our production  site runs we don't get this error.

**Comment by chriswheeler** [comment]
Yes, the issue here stems from PHP8 converting a number of previous Notices into Warnings - https://www.php.net/manual/en/migration80.incompatible.php

I suppose the questions is - is it the responsibility of Smarty to change the PHP code it generates to maintain the existing behaviour, or template authors to change their template code?

**Comment by Bigbear7** [comment]
For sure that is the case and the vote for that specific case was 42 - 21 in the RFC Reclassifying engine warnings, so one vote...

It's a fair question to ask whether it's a Smarty or the application using smarty responsiblity. For me in order to judge that I need to look into our own code a bit more. This code has been running flawlessly for quite some time, so hopefully there is a smooth  way around it.

Anyway, typically the compiled smarty code that flunks has typically the structure, where the 'key' is undefined:
- $_smarty_tpl->tpl_vars['key']->value

**Comment by bhsmither** [comment]
I could concur that using `|default:''` everywhere is a fine solution. But if this is used 'everywhere' whether it is needed or not, whether there is an expected null-ness or not expected, I would wonder why Smarty doesn't do this for us already.

**Comment by timmit-nl** [comment]
but what should be the default value be? `null`, `false`, `''`? and where to stop? 

ok if we all want to, I can life with a default `null`. I think we need to modify smarty that everywhere where `$xxxxxx` stands it is replace it with `($_smarty_tpl->tpl_vars['xxxxxx']->value ?? null)`.
I don't know the smarty classes good enough to say this can be done easy.

**Comment by bhsmither** [comment]
I would hope that muteExpectedErrors() would take care of the (now) Warnings for undefined variables and properties. And I, personally, would add an undefined key as being similar to an undefined variable. But none of the other "Notices are now Warnings" (http://docs.php.net/manual/en/migration80.incompatible.php).

I believe PHP does not stop running the script on Warnings -- which my assertion is that executing compiled/cached Smarty template scripts does stop running (i.e., an 'abend') under PHP8.

I also think that _null_, _false_, or a zero-length-string, in this context, are distinctions with no difference. None of them contribute anything to the output string.

**Comment by Bigbear7** [comment]
No, the application and compiled smarty scripts doesn't stop running, but the logs are flooded with warnings. Anyway, my quick & dirty fix for this is to mute warnings in smarty with:
- $smarty->setErrorReporting(E_ALL & ~E_WARNING & ~E_NOTICE);

**Comment by wisskid** [comment]
@bhsmither  `muteExpectedErrors` has been deprecated since 2017, so I'm considering removing it, along with `Smarty_Internal_ErrorHandler` because Smarty no longer uses `@filemtime()` calls. We could re-use the concept though and activate it by default for PHP8 so Undefined array key and trying to read property of null warnings will be rethrown as notices.

**Comment by wisskid** [comment]
#629 now includes support for `$smarty->setPHP7CompatMode()` that will make Smarty ignore E_WARNINGS for undefined variables, array keys, et cetera. Rethrowing them as E_NOTICES is not possible. A side-effect is that some errors occurring in business logic called from the template source will also be silenced.
Therefore, I figured it would be better to not enable this by default. It's not very pretty, but it does the trick, I think.

**Comment by chriswheeler** [comment]
#626 now works well for be under PHP8 with no log lines generated after I'd turned on setPHP7CompatMode().

It's a minor point, but I'm not sure that's the best naming, It might make people think they have to have it turned on for Smarty to be compatible *with* PHP7...

Would it be better to just tweak muteExpectedErrors(), - rather than removing it and replacing it with setPHP7CompatMode()? 

Both does something very similar, and anyone who was using muteExpectedErrors() (as I was) would probably also now want to use setPHP7CompatMode(). I can see my self simply replacing muteExpectedErrors() with setPHP7CompatMode() on a number of sites as I upgrade them to PHP8.

**Comment by bhsmither** [comment]
I vote for tweaking `muteExpectedErrors()` to also do what `setPHP7CompatMode()` would do - if practicable.

I regularly run into situations where access to the source PHP code is not allowed or simply not possible.

Which supports the idea of creating corresponding Smarty in-template commands - but that's a different issue.

**Comment by Bigbear7** [comment]
Regarding naming I wonder if this is more related with PHP 8 rather then PHP 7, so should it be called $smarty->setPHP8CompatMode() if not muteExpectedErrors()? But maybe it should handle other PHP 7 aspects?

Anyway, for our site smarty 3.1.36 runs flawlessly on it with PHP 7.4.

**Comment by tzcsx** [comment]
I am migrating a legacy application to PHP 8 and running into the mentioned _Undefined array key_ E_WARNINGs. I am aware of the approach Smarty 4 has taken but unfortunately I can not upgrade to Smarty 4. I like @timmit-nl 's approach of patching Smarty's code generation using the null coalescing operator. However [the suggested change](https://github.com/smarty-php/smarty/issues/617#issuecomment-760397615) to `compileVariable` does not quite work.
`{$foo.bar}` is compiled to `$_smarty_tpl->tpl_vars['foo']->value ?? null)['bar']` which will not work. Expected output is `$_smarty_tpl->tpl_vars['foo']->value['bar'] ?? null)`. I am currently digging into Smarty to adapt this myself but would really appreciate any hints.
Cheers

**Comment by timmit-nl** [comment]
the suggested change isn't tested and I have only written it as an example. We use everywhere |default: xx} as we want to know if something is not set....

**Comment by tzcsx** [comment]
Thanks for jumping back into this, timmit-nl. Yes of course the default filter would be a proper solution but introducing this into the legacy code base I have to work with unfortunately is not feasible. Your example code actually does work for `{$foo}` which is why I am motivated to adapt it to work with `{$foo.bar}` as well.

**Comment by tzcsx** [comment]
To my humble understanding of the grammar in [lexer/smarty_internal_templateparser.y](https://github.com/smarty-php/smarty/blob/master/lexer/smarty_internal_templateparser.y) this approach is not going to work. Due to the object and array style nesting capabilities of Smarty,  I would need to introduce a new expression to match a complete nesting statement. Guess this finally means EOL for legacy applications. Still very much open to suggestions.

**Comment by wisskid** [comment]
The setPHP7CompatMode method has been renamed due to popular demand in https://github.com/smarty-php/smarty/pull/629 :)

I'm not in favor of reusing the deprectated muteExpectedErrors() as that did something completely different.

Planning to release https://github.com/smarty-php/smarty/pull/629 as Smarty 4 soon (tm), unless someone encounters serious problems testing on php8 before.

**Comment by chriswheeler** [comment]
Note to future self when searching for this: setPHP7CompatMode() was renamed to muteUndefinedOrNullWarnings()

**Comment by Bigbear7** [comment]
Well, I have tested the php8-support branch and it runs nicely!

However, I had some HTML code commented out with  and somehow it looks like it got parsed. And of course that generated a lot of warnings that was relevant.

Another small comment is that on line 644, 1380 & 1390 is says PHP7 compatibility. Think it should be PHP8 compatibility.

**Comment by Bigbear7** [comment]
Well, I have tested the php8-support branch and it runs nicely!

However, I had some HTML code commented out with and somehow it looks like it got parsed. And of course that generated a lot of warnings that was relevant. The warnings vanished once I removed the commented out HTML.

Another small comment is that on line 644, 1380 & 1390iin Smarty.class.php is says PHP7 compatibility. Think it should be PHP8 compatibility.

**Comment by Bigbear7** [comment]
Well, I have tested the php8-support branch and it runs nicely!

However, I had some HTML code within comments () and somehow it looks like it got parsed. And of course that generated a lot of warnings that was relevant. The warnings vanished once I removed the commented HTML code.

Another small comment is that on line 644, 1380 & 1390 in Smarty.class.php is says PHP7 compatibility. Think it should be PHP8 compatibility.
